### ISSUE TITLE
Change cursor to pointer when hovering buttons

### ISSUE THREAD

**Issue by danielwerg** [AMNatty/wleave#7]
I tried:

```css
button {
  cursor: pointer;
}
```

But that breaks everything, and turns colors gray. I guess it is gtk issue/limitation? Is there a way to change cursor somehow else?
