### ISSUE TITLE
Spawn window on all monitors

### ISSUE THREAD

**Issue by danielwerg** [AMNatty/wleave#9]
wleave spawn on only on `current` monitor. I would like to have wleave spawn window on _every_ secondary monitor, then I would apply styles:

```css
window {
  background-color: rgba(12, 12, 12, 0.8);
}
```

I do not want layout on secondary monitors.
